import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { Roboto_Slab, Arvo } from "next/font/google";
import Footer from "./components/Footer";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const arvo = Arvo({
  variable: "--font-arvo",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const robotoSlab = Roboto_Slab({
  variable: "--font-roboto-slab",
  subsets: ["latin"],
});

const domaineDisplay = localFont({
  src: [
    {
      path: "/fonts/TestDomaineDisplay-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-domaine-display",
});

const dramaDisplay = localFont({
  src: [
    {
      path: "/fonts/Drama-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-drama-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${domaineDisplay.variable} ${dramaDisplay.variable} ${robotoSlab.variable} ${arvo.variable} overflow-x-hidden antialiased w-full`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
